baseurl: ''
url: http://dhlab.yale.edu

# render posts with dates in the future
future: true

# minify html in production
minify_html: true

# create lunr index
create_index: true

# bust cache
bust_cache: true

# minify js
compress_js: true

# minify assets
sass:
  style: compressed
  load_paths: 
    - node_modules

# render collections
collections:
  resources:
    output: true
  events:
    output: true
  news:
    output: true
  projects:
    output: true
  guides:
    output: true
  methods:
    output: true
  awards:
    output: true
  opportunities:
    output: true
  team:
    output: false
  about:
    output: true

# default layouts
defaults:
  - scope:
      path: ''
      type: 'news'
    values:
      layout: news
  - scope:
      path: ''
      type: 'events'
    values:
      layout: event
  - scope:
      path: ''
      type: 'guides'
    values:
      layout: guide
  - scope:
      path: ''
      type: 'methods'
    values:
      layout: method
  - scope:
      path: ''
      type: 'projects'
    values:
      layout: project
  - scope:
      path: ''
      type: 'resources'
    values:
      layout: resource
  - scope:
      path: ''
      type: 'awards'
    values:
      layout: award
  - scope:
      path: ''
      type: 'opportunities'
    values:
      layout: opportunity

# social media
twitter: YaleDHLab
instagram: yaledhlab
facebook: YaleDHLab
github: YaleDHLab
email: dhlab@yale.edu
phone: 203-432-123

# newsletter url
newsletter: 'https://subscribe.yale.edu/browse?search=digital+humanities'

# submit news url
submit_news: 'https://docs.google.com/forms/d/1HvwWecpYODW3DoMVTnJy7beOMfechLPIiVhV5ekvYNI'

# request consultation
consultation: 'https://docs.google.com/forms/d/e/1FAIpQLSe4Lyo8EEdoiTLosfnmOUNEsZZToCD_n7dZ10ypCerw4diJGA/viewform?usp=sf_link'

# configure gems
plugins:
  - octopress-minify-html

# minify css and js with webpack
keep_files:
  - 'assets/bundle.js'
  - 'assets/js/search/index.json'
  - 'assets/js/search/id-to-metadata.json'

# exclude node files from build directory
exclude:
  - 'node_modules'
  - 'utils'
  - 'yarn.lock'
  - 'package.json'
  - '.jekyll-metadata'
  - 'Gemfile.lock'
  - 'Gemfile'
  - 'README.md'